=== hestiacn/vstats/wwwroot/icon/os/awstats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="comment" type="xs:string"/>
	<xs:element name="lib" type="xs:string"/>
	<xs:element name="nu" type="xs:string"/>
	<xs:element name="recnb" type="xs:integer"/>
	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sortfor" minOccurs="0"/>
				<xs:element ref="comment"/>
				<xs:element ref="nu"/>
				<xs:element ref="recnb"/>
				<xs:element ref="table"/>
				<xs:element ref="nu"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="browser"/>
						<xs:enumeration value="cluster"/>
						<xs:enumeration value="day"/>
						<xs:enumeration value="device"/>
						<xs:enumeration value="domain"/>
						<xs:enumeration value="downloads"/>
						<xs:enumeration value="emailreceiver"/>
						<xs:enumeration value="emailsender"/>
						<xs:enumeration value="errors"/>
						<xs:enumeration value="extra_1"/>
						<xs:enumeration value="filetypes"/>
						<xs:enumeration value="filesize"/>
						<xs:enumeration value="general"/>
						<xs:enumeration value="header"/>
						<xs:enumeration value="iconstatus"/>
						<xs:enumeration value="keywords"/>
						<xs:enumeration value="login"/>
						<xs:enumeration value="misc"/>
						<xs:enumeration value="origin"/>
						<xs:enumeration value="os"/>
						<xs:enumeration value="pagerefs"/>
						<xs:enumeration value="protocol"/>
						<xs:enumeration value="requesttime"/>
						<xs:enumeration value="robot"/>
						<xs:enumeration value="screensize"/>
						<xs:enumeration value="searchwords"/>
						<xs:enumeration value="sereferrals"/>
						<xs:enumeration value="session"/>
						<xs:enumeration value="sider"/>
						<xs:enumeration value="sider_404"/>
						<xs:enumeration value="time"/>
						<xs:enumeration value="unknownreferer"/>
						<xs:enumeration value="unknownrefererbrowser"/>
						<xs:enumeration value="visitor"/>
						<xs:enumeration value="worms"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sortfor">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="10"/>
				<xs:enumeration value="20"/>
				<xs:enumeration value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="table">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tr"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="td" type="xs:string"/>
	<xs:element name="tr">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="td" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="version">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lib"/>
				<xs:element ref="comment"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="xml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="version"/>
				<xs:element ref="section" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hestiacn/vstats/tools/xslt/awstats.datademo2.xml
<xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.awstats.org/files/awstats.xsd">

<version><lib>
AWSTATS DATA FILE 6.7 (build 1.892)
</lib><comment>
# If you remove this file, all statistics for date 200101 will be lost/reset.
</comment></version>

<section id='header'><comment>
# Position (offset in bytes) in this file of beginning of each section for
# direct I/O access. If you made changes somewhere in this file, you should
# also remove completely the MAP section (AWStats will rewrite it at next
# update).
</comment><nu>
BEGIN_MAP</nu><recnb>29</recnb><table>
<tr><td>POS_GENERAL</td><td>3010                </td></tr>
<tr><td>POS_TIME</td><td>4512                </td></tr>
<tr><td>POS_VISITOR</td><td>6899                </td></tr>
<tr><td>POS_DAY</td><td>7712                </td></tr>
<tr><td>POS_DOMAIN</td><td>8031                </td></tr>
<tr><td>POS_LOGIN</td><td>8577                </td></tr>
<tr><td>POS_ROBOT</td><td>8939                </td></tr>
<tr><td>POS_WORMS</td><td>9441                </td></tr>
<tr><td>POS_EMAILSENDER</td><td>9770                </td></tr>
<tr><td>POS_EMAILRECEIVER</td><td>10041               </td></tr>
<tr><td>POS_SESSION</td><td>10218               </td></tr>
<tr><td>POS_SIDER</td><td>10510               </td></tr>
<tr><td>POS_FILETYPES</td><td>11318               </td></tr>
<tr><td>POS_OS</td><td>11863               </td></tr>
<tr><td>POS_BROWSER</td><td>12222               </td></tr>
<tr><td>POS_SCREENSIZE</td><td>12638               </td></tr>
<tr><td>POS_UNKNOWNREFERER</td><td>12857               </td></tr>
<tr><td>POS_UNKNOWNREFERERBROWSER</td><td>13059               </td></tr>
<tr><td>POS_ORIGIN</td><td>13241               </td></tr>
<tr><td>POS_SEREFERRALS</td><td>13681               </td></tr>
<tr><td>POS_PAGEREFS</td><td>13989               </td></tr>
<tr><td>POS_SEARCHWORDS</td><td>14674               </td></tr>
<tr><td>POS_KEYWORDS</td><td>14993               </td></tr>
<tr><td>POS_MISC</td><td>3658                </td></tr>
<tr><td>POS_ERRORS</td><td>15196               </td></tr>
<tr><td>POS_CLUSTER</td><td>8315                </td></tr>
<tr><td>POS_SIDER_404</td><td>15504               </td></tr>
<tr><td>POS_EXTRA_1</td><td>15863               </td></tr>
<tr><td>POS_EXTRA_2</td><td>16257               </td></tr>
</table><nu>END_MAP
</nu></section>

<section id='general'><comment>
# LastLine    = Date of last record processed - Last record line number in last log - Last record offset in last log - Last record signature value
# FirstTime   = Date of first visit for history file
# LastTime    = Date of last visit for history file
# LastUpdate  = Date of last update - Nb of parsed records - Nb of parsed old records - Nb of parsed new records - Nb of parsed corrupted - Nb of parsed dropped
# TotalVisits = Number of visits
# TotalUnique = Number of unique visitors
# MonthHostsKnown   = Number of hosts known
# MonthHostsUnKnown = Number of hosts unknown
</comment><nu>
BEGIN_GENERAL</nu><recnb>8</recnb><table>
<tr><td>LastLine</td><td>20010101170000 84 10496 69181820316</td></tr>
<tr><td>FirstTime</td><td>20010101000010</td></tr>
<tr><td>LastTime</td><td>20010101163000</td></tr>
<tr><td>LastUpdate</td><td>20070712233159 84 0 45 38 1</td></tr>
<tr><td>TotalVisits</td><td>5                   </td></tr>
<tr><td>TotalUnique</td><td>4                   </td></tr>
<tr><td>MonthHostsKnown</td><td>6                   </td></tr>
<tr><td>MonthHostsUnknown</td><td>0                   </td></tr>
</table><nu>
END_GENERAL
</nu></section>

<section id='misc'><comment>
# Misc ID - Pages - Hits - Bandwidth
</comment><nu>
BEGIN_MISC</nu><recnb>10</recnb><table>
<tr><td>QuickTimeSupport</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>JavaEnabled</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>JavascriptDisabled</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>PDFSupport</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>WindowsMediaPlayerSupport</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>AddToFavourites</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>RealPlayerSupport</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>TotalMisc</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td>DirectorSupport</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>FlashSupport</td><td>0</td><td>1</td><td>0</td></tr>
</table><nu>END_MISC
</nu></section>

<section id='time'><comment>
# Hour - Pages - Hits - Bandwidth - Not viewed Pages - Not viewed Hits - Not viewed Bandwidth
</comment><nu>
BEGIN_TIME</nu><recnb>24</recnb><table>
<tr><td>0</td><td>4</td><td>6</td><td>42054</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>8</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>9</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>12</td><td>8</td><td>16</td><td>108122</td><td>3</td><td>3</td><td>7607</td></tr>
<tr><td>13</td><td>2</td><td>2</td><td>14018</td><td>1</td><td>6</td><td>8829</td></tr>
<tr><td>14</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td></tr>
<tr><td>15</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>299</td></tr>
<tr><td>16</td><td>6</td><td>6</td><td>422856</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>17</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>70476</td></tr>
<tr><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</table><nu>END_TIME
</nu></section>

<section id='visitor'><sortfor>25</sortfor><comment>
# Host - Pages - Hits - Bandwidth - Last visit date - [Start date of last visit] - [Last page of last visit]
# [Start date of last visit] and [Last page of last visit] are saved only if session is not finished
# The 25 first Hits must be first (order not required for others)
</comment><nu>
BEGIN_VISITOR</nu><recnb>6</recnb><table>
<tr><td>camarche</td><td>8</td><td>14</td><td>94104</td><td>20010101120025</td></tr>
<tr><td>alamentin-104-1-77-10.w80-8.abo.wanadoo.fr</td><td>6</td><td>6</td><td>422856</td><td>20010101163000</td><td>20010101160000</td><td>/page1.html</td></tr>
<tr><td>alamentin-104-1-77-3.w80-8.abo.wanadoo.fr</td><td>4</td><td>6</td><td>42054</td><td>20010101120125</td></tr>
<tr><td>camarchesuperbienmeme</td><td>2</td><td>2</td><td>14018</td><td>20010101130100</td></tr>
<tr><td>camarchetresbienmeme</td><td>0</td><td>1</td><td>7009</td><td></td></tr>
<tr><td>alamentin-104-1-77-2.w80-8.abo.wanadoo.fr</td><td>0</td><td>1</td><td>7009</td><td></td></tr>
</table><nu>END_VISITOR
</nu></section>

<section id='day'><comment>
# Date - Pages - Hits - Bandwidth - Visits
</comment><nu>
BEGIN_DAY</nu><recnb>1</recnb><table>
<tr><td>20010101</td><td>20</td><td>30</td><td>587050</td><td>5</td></tr>
</table><nu>END_DAY
</nu></section>

<section id='domain'><sortfor>25</sortfor><comment>
# Domain - Pages - Hits - Bandwidth
# The 25 first Pages must be first (order not required for others)
</comment><nu>
BEGIN_DOMAIN</nu><recnb>2</recnb><table>
<tr><td>fr</td><td>10</td><td>13</td><td>471919</td></tr>
<tr><td>ip</td><td>10</td><td>17</td><td>115131</td></tr>
</table><nu>END_DOMAIN
</nu></section>

<section id='cluster'><comment>
# Cluster ID - Pages - Hits - Bandwidth
</comment><nu>
BEGIN_CLUSTER</nu><recnb>0</recnb><table>
</table><nu>END_CLUSTER
</nu></section>

<section id='login'><sortfor>5</sortfor><comment>
# Login - Pages - Hits - Bandwidth - Last visit
# The 5 first Pages must be first (order not required for others)
</comment><nu>
BEGIN_LOGIN</nu><recnb>1</recnb><table>
<tr><td>john_begood</td><td>2</td><td>2</td><td>14018</td><td>20010101130100</td></tr>
</table><nu>END_LOGIN
</nu></section>

<section id='robot'><sortfor>25</sortfor><comment>
# Robot ID - Hits - Bandwidth - Last visit - Hits on robots.txt
# The 25 first Hits must be first (order not required for others)
</comment><nu>
BEGIN_ROBOT</nu><recnb>3</recnb><table>
<tr><td>up\.browser</td><td>6</td><td>8829</td><td>20010101130000</td><td>0</td></tr>
<tr><td>googlebot</td><td>2</td><td>7308</td><td>20010101120205</td><td>1</td></tr>
<tr><td>unknown</td><td>1</td><td>299</td><td>20010101120200</td><td>1</td></tr>
</table><nu>END_ROBOT
</nu></section>

<section id='worms'><sortfor>5</sortfor><comment>
# Worm ID - Hits - Bandwidth - Last visit
# The 5 first Hits must be first (order not required for others)
</comment><nu>
BEGIN_WORMS</nu><recnb>1</recnb><table>
<tr><td>code_red</td><td>1</td><td>299</td><td>20010101150000</td></tr>
</table><nu>END_WORMS
</nu></section>

<section id='emailsender'><sortfor>20</sortfor><comment>
# EMail - Hits - Bandwidth - Last visit
# The 20 first Hits must be first (order not required for others)
</comment><nu>
